apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-storage-elasticsearch-0
  namespace: elk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage