apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
data:
  fluent-bit.conf: |
    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        Parser docker
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

    [OUTPUT]
        Name es
        Match *
        Host elasticsearch
        Port 9200
        Logstash_Format On
        Logstash_Prefix logs
        Replace_Dots On
        Retry_Limit False