apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-pv
spec:
  capacity:
    storage: 2Gi  # Allocate 2 GB of storage
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi  # Request 2 GB of storage
  storageClassName: local-storage
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: todo-app-db
spec:
  instances: 1
  storage:
    size: 2Gi
    storageClass: local-storage
  bootstrap:
    initdb:
      database: todo_db
      owner: todo_user
  primaryUpdateStrategy: unsupervised