apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  host: dG9kby1hcHAtZGIucncuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbA==  # "todo-app-db-rw.default.svc.cluster.local"
  username: dG9kb191c2Vy  # "todo_user"
  password: cGFzc3dvcmQxMjM=  # "password123"